name: simver
description: "simple semantic versioning"
inputs: { GITHUB_TOKEN: { description: "GitHub token", required: true } }
runs:
    using: "composite"
    steps:
    - name: checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: print git context
      shell: bash
      run: "jq . -r <<< '${{ toJson(github) }}' | tee /dev/stderr"
    - name: get current action  ref
      id: get-action-ref
      shell: bash
      run: "echo \"SIMVER_GITHUB_ACTION_REF=${{ github.action_ref }}\" >> $GITHUB_ENV"
    - name: checkout simver code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: walteh/simver
        ref: ${{ env.SIMVER_GITHUB_ACTION_REF }}
        path: "__simver__"
    - name: get current go version from go.mod
      id: go-version
      shell: bash
      run: 'cat __simver__/go.mod | grep ''go '' | awk ''{print $2}'' | xargs -I {} echo "GO_VERSION={}" >> $GITHUB_ENV'
    - name: setup golang
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: install dependencies
      shell: bash
      run: "cd __simver__ && go mod download"
    - name: install simver
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: "go run ./__simver__/cmd/simver_gha --read-only=false"
