name: simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, closed]
jobs:
    simver:
        runs-on: ubuntu-latest
        steps:
            - uses: walteh/simver/cmd/gha-simver@02d3e1088279a80e69a806c334812a90caa6d1db
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
