name: wait-on-simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: ["*"]
jobs:
    wait-on-simver:
        runs-on: ubuntu-latest
        steps:
            - uses: walteh/simver/cmd/gha-wait-on-simver@a9f89e2fb17b03b3150c2aed050a68bc85280f02
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
