name: wait-on-simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, closed]
jobs:
    simver:
        runs-on: ubuntu-latest
        steps:
            - uses: walteh/simver/cmd/gha-wait-on-simver@d80fe3db5062c061d36a887e3626f158965d970d
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
