name: wait-on-simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, closed]
jobs:
    simver:
        runs-on: ubuntu-latest
        steps:
            - uses: walteh/simver/cmd/gha-wait-on-simver@7d12a7dadbd7cc209807f86b2d6e85b26d6d7fec
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
